version: 2
cli:
    server: https://app.fossa.com
    fetcher: custom
    project: kitx
analyze:
    modules:
        -   name: github.com/sagikazarmark/kitx
            type: go
            target: github.com/sagikazarmark/kitx
            strategy: gomodules
            path: .
            options:
                allow-unresolved: true
