linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/sagikazarmark/kitx

linters:
    enable-all: true
    disable:
        - funlen

service:
    golangci-lint-version: 1.19.x
