linters-settings:
    gci:
        sections:
            - standard
            - default
            - prefix(github.com/sagikazarmark/kitx)
    goimports:
        local-prefixes: github.com/sagikazarmark/kitx

linters:
    presets:
        - bugs
        - unused
        - format
        - import
    disable:
        - noctx
        - depguard
