name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop -c bash {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: make lint
        env:
          LINT_ARGS: --out-format=github-actions

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1_22", "1_23"]
    defaults:
      run:
        shell: nix develop .#ci${{ matrix.go }} -c bash {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: make test

      - name: Annotate tests
        uses: guyarb/golang-test-annotations@v0.8.0
        if: always()
        with:
          test-results: build/test.json

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.txt
